### ISSUE TITLE
KeyError: 'STRANDED'

### ISSUE THREAD

**Issue by asaravia-butler** [J-81/dp_tools#40] opened 2023-11-06 01:13 UTC
START OSD-101

pull metrics

2023-11-05 22:41:51.051 | DEBUG    | dp_tools.core.files.isa_archive:fetch_isa_files:29 - Extracting ISA Archive to temp directory: /tmp/tmpx_iimvuj
2023-11-05 22:41:51.081 | DEBUG    | dp_tools.core.files.isa_archive:fetch_isa_files:29 - Extracting ISA Archive to temp directory: /tmp/tmp7w228rmk
2023-11-05 22:41:51.103 | DEBUG    | dp_tools.core.files.isa_archive:fetch_isa_files:29 - Extracting ISA Archive to temp directory: /tmp/tmp8rrn5wxe
2023-11-05 22:41:51.107 | DEBUG    | dp_tools.core.files.isa_archive:fetch_isa_files:29 - Extracting ISA Archive to temp directory: /tmp/tmp9vjhl2o0
2023-11-05 22:41:51.128 | DEBUG    | dp_tools.core.files.isa_archive:fetch_isa_files:29 - Extracting ISA Archive to temp directory: /tmp/tmpeqbzx2sk
2023-11-05 22:41:51.130 | DEBUG    | dp_tools.core.files.isa_archive:fetch_isa_files:29 - Extracting ISA Archive to temp directory: /tmp/tmpv4rqe__y
Traceback (most recent call last):
  File "/workspace/dp_tools/multiQC_output_ASB/PE_datasets_w_raw_trim_align_multiQC/OSD-101/../../../extract_dataset.py", line 36, in <module>
    main()
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/dp_tools/multiQC_output_ASB/PE_datasets_w_raw_trim_align_multiQC/OSD-101/../../../extract_dataset.py", line 21, in main
    metricsExtractor.extract_data_from_isa(
  File "/workspace/dp_tools/dp_tools/core/utilites/metrics_extractor.py", line 307, in extract_data_from_isa
    samplewise_metrics = convert.isa_to_runsheet(
  File "/workspace/dp_tools/dp_tools/scripts/convert.py", line 375, in isa_to_runsheet
    df_final[entry["Runsheet Column Name"]] = series_to_add.map(
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/pandas/core/series.py", line 4237, in map
    new_values = self._map_values(arg, na_action=na_action)
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/pandas/core/base.py", line 880, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/workspace/dp_tools/dp_tools/scripts/convert.py", line 376, in <lambda>
    lambda val: entry.get("Remapping")[val]
KeyError: 'STRANDED'

**Comment by J-81** [comment] 2023-11-08 01:32
Root cause: ISA Table has these columns mixed up (`library layout` & `stranded`)

Workaround:

* Swap ` Runsheet Column Name:` & `Remapping:` here (keep commented out line): https://github.com/J-81/dp_tools/blob/d2695db6cabbb6f7f5a0c88d08c9fd194ceb8e84/assets/isa_config.yaml#L83-L94

**Comment by J-81** [comment] 2023-11-08 01:33
Closing due to issue being malformed metadata

**Closed as completed by J-81** 2023-11-08 01:33 UTC
